// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: event.proto

#include "event.pb.h"
#include "event.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace helium3 {
namespace logging {

static const char* Logger_method_names[] = {
  "/helium3.logging.Logger/LogEvent",
};

std::unique_ptr< Logger::Stub> Logger::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Logger::Stub> stub(new Logger::Stub(channel));
  return stub;
}

Logger::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_LogEvent_(Logger_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Logger::Stub::LogEvent(::grpc::ClientContext* context, const ::helium3::logging::EventMsg& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_LogEvent_, context, request, response);
}

void Logger::Stub::experimental_async::LogEvent(::grpc::ClientContext* context, const ::helium3::logging::EventMsg* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_LogEvent_, context, request, response, std::move(f));
}

void Logger::Stub::experimental_async::LogEvent(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_LogEvent_, context, request, response, std::move(f));
}

void Logger::Stub::experimental_async::LogEvent(::grpc::ClientContext* context, const ::helium3::logging::EventMsg* request, ::google::protobuf::Empty* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_LogEvent_, context, request, response, reactor);
}

void Logger::Stub::experimental_async::LogEvent(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::google::protobuf::Empty* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_LogEvent_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* Logger::Stub::AsyncLogEventRaw(::grpc::ClientContext* context, const ::helium3::logging::EventMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::google::protobuf::Empty>::Create(channel_.get(), cq, rpcmethod_LogEvent_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* Logger::Stub::PrepareAsyncLogEventRaw(::grpc::ClientContext* context, const ::helium3::logging::EventMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::google::protobuf::Empty>::Create(channel_.get(), cq, rpcmethod_LogEvent_, context, request, false);
}

Logger::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Logger_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Logger::Service, ::helium3::logging::EventMsg, ::google::protobuf::Empty>(
          [](Logger::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::helium3::logging::EventMsg* req,
             ::google::protobuf::Empty* resp) {
               return service->LogEvent(ctx, req, resp);
             }, this)));
}

Logger::Service::~Service() {
}

::grpc::Status Logger::Service::LogEvent(::grpc::ServerContext* context, const ::helium3::logging::EventMsg* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace helium3
}  // namespace logging

