// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_event_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_event_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/empty.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_event_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_event_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_event_2eproto;
namespace helium3 {
namespace logging {
class EventMsg;
class EventMsgDefaultTypeInternal;
extern EventMsgDefaultTypeInternal _EventMsg_default_instance_;
}  // namespace logging
}  // namespace helium3
PROTOBUF_NAMESPACE_OPEN
template<> ::helium3::logging::EventMsg* Arena::CreateMaybeMessage<::helium3::logging::EventMsg>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace helium3 {
namespace logging {

// ===================================================================

class EventMsg PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:helium3.logging.EventMsg) */ {
 public:
  inline EventMsg() : EventMsg(nullptr) {};
  virtual ~EventMsg();

  EventMsg(const EventMsg& from);
  EventMsg(EventMsg&& from) noexcept
    : EventMsg() {
    *this = ::std::move(from);
  }

  inline EventMsg& operator=(const EventMsg& from) {
    CopyFrom(from);
    return *this;
  }
  inline EventMsg& operator=(EventMsg&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const EventMsg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const EventMsg* internal_default_instance() {
    return reinterpret_cast<const EventMsg*>(
               &_EventMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(EventMsg& a, EventMsg& b) {
    a.Swap(&b);
  }
  inline void Swap(EventMsg* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EventMsg* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline EventMsg* New() const final {
    return CreateMaybeMessage<EventMsg>(nullptr);
  }

  EventMsg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<EventMsg>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const EventMsg& from);
  void MergeFrom(const EventMsg& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EventMsg* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "helium3.logging.EventMsg";
  }
  protected:
  explicit EventMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_event_2eproto);
    return ::descriptor_table_event_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMachineIdFieldNumber = 1,
    kNameFieldNumber = 3,
    kMessageFieldNumber = 6,
    kStartNsFieldNumber = 4,
    kStateFieldNumber = 2,
    kCompleteFieldNumber = 7,
    kDurationNsFieldNumber = 5,
  };
  // string machine_id = 1;
  void clear_machine_id();
  const std::string& machine_id() const;
  void set_machine_id(const std::string& value);
  void set_machine_id(std::string&& value);
  void set_machine_id(const char* value);
  void set_machine_id(const char* value, size_t size);
  std::string* mutable_machine_id();
  std::string* release_machine_id();
  void set_allocated_machine_id(std::string* machine_id);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_machine_id();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_machine_id(
      std::string* machine_id);
  private:
  const std::string& _internal_machine_id() const;
  void _internal_set_machine_id(const std::string& value);
  std::string* _internal_mutable_machine_id();
  public:

  // string name = 3;
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_name();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_name(
      std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string message = 6;
  void clear_message();
  const std::string& message() const;
  void set_message(const std::string& value);
  void set_message(std::string&& value);
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  std::string* mutable_message();
  std::string* release_message();
  void set_allocated_message(std::string* message);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_message();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_message(
      std::string* message);
  private:
  const std::string& _internal_message() const;
  void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // int64 start_ns = 4;
  void clear_start_ns();
  ::PROTOBUF_NAMESPACE_ID::int64 start_ns() const;
  void set_start_ns(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_start_ns() const;
  void _internal_set_start_ns(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int32 state = 2;
  void clear_state();
  ::PROTOBUF_NAMESPACE_ID::int32 state() const;
  void set_state(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_state() const;
  void _internal_set_state(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // bool complete = 7;
  void clear_complete();
  bool complete() const;
  void set_complete(bool value);
  private:
  bool _internal_complete() const;
  void _internal_set_complete(bool value);
  public:

  // int64 duration_ns = 5;
  void clear_duration_ns();
  ::PROTOBUF_NAMESPACE_ID::int64 duration_ns() const;
  void set_duration_ns(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_duration_ns() const;
  void _internal_set_duration_ns(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // @@protoc_insertion_point(class_scope:helium3.logging.EventMsg)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr machine_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
  ::PROTOBUF_NAMESPACE_ID::int64 start_ns_;
  ::PROTOBUF_NAMESPACE_ID::int32 state_;
  bool complete_;
  ::PROTOBUF_NAMESPACE_ID::int64 duration_ns_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_event_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// EventMsg

// string machine_id = 1;
inline void EventMsg::clear_machine_id() {
  machine_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& EventMsg::machine_id() const {
  // @@protoc_insertion_point(field_get:helium3.logging.EventMsg.machine_id)
  return _internal_machine_id();
}
inline void EventMsg::set_machine_id(const std::string& value) {
  _internal_set_machine_id(value);
  // @@protoc_insertion_point(field_set:helium3.logging.EventMsg.machine_id)
}
inline std::string* EventMsg::mutable_machine_id() {
  // @@protoc_insertion_point(field_mutable:helium3.logging.EventMsg.machine_id)
  return _internal_mutable_machine_id();
}
inline const std::string& EventMsg::_internal_machine_id() const {
  return machine_id_.Get();
}
inline void EventMsg::_internal_set_machine_id(const std::string& value) {
  
  machine_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void EventMsg::set_machine_id(std::string&& value) {
  
  machine_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:helium3.logging.EventMsg.machine_id)
}
inline void EventMsg::set_machine_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  machine_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:helium3.logging.EventMsg.machine_id)
}
inline void EventMsg::set_machine_id(const char* value,
    size_t size) {
  
  machine_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:helium3.logging.EventMsg.machine_id)
}
inline std::string* EventMsg::_internal_mutable_machine_id() {
  
  return machine_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* EventMsg::release_machine_id() {
  // @@protoc_insertion_point(field_release:helium3.logging.EventMsg.machine_id)
  return machine_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void EventMsg::set_allocated_machine_id(std::string* machine_id) {
  if (machine_id != nullptr) {
    
  } else {
    
  }
  machine_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), machine_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:helium3.logging.EventMsg.machine_id)
}
inline std::string* EventMsg::unsafe_arena_release_machine_id() {
  // @@protoc_insertion_point(field_unsafe_arena_release:helium3.logging.EventMsg.machine_id)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return machine_id_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void EventMsg::unsafe_arena_set_allocated_machine_id(
    std::string* machine_id) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (machine_id != nullptr) {
    
  } else {
    
  }
  machine_id_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      machine_id, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:helium3.logging.EventMsg.machine_id)
}

// int32 state = 2;
inline void EventMsg::clear_state() {
  state_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 EventMsg::_internal_state() const {
  return state_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 EventMsg::state() const {
  // @@protoc_insertion_point(field_get:helium3.logging.EventMsg.state)
  return _internal_state();
}
inline void EventMsg::_internal_set_state(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  state_ = value;
}
inline void EventMsg::set_state(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_state(value);
  // @@protoc_insertion_point(field_set:helium3.logging.EventMsg.state)
}

// string name = 3;
inline void EventMsg::clear_name() {
  name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& EventMsg::name() const {
  // @@protoc_insertion_point(field_get:helium3.logging.EventMsg.name)
  return _internal_name();
}
inline void EventMsg::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:helium3.logging.EventMsg.name)
}
inline std::string* EventMsg::mutable_name() {
  // @@protoc_insertion_point(field_mutable:helium3.logging.EventMsg.name)
  return _internal_mutable_name();
}
inline const std::string& EventMsg::_internal_name() const {
  return name_.Get();
}
inline void EventMsg::_internal_set_name(const std::string& value) {
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void EventMsg::set_name(std::string&& value) {
  
  name_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:helium3.logging.EventMsg.name)
}
inline void EventMsg::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:helium3.logging.EventMsg.name)
}
inline void EventMsg::set_name(const char* value,
    size_t size) {
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:helium3.logging.EventMsg.name)
}
inline std::string* EventMsg::_internal_mutable_name() {
  
  return name_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* EventMsg::release_name() {
  // @@protoc_insertion_point(field_release:helium3.logging.EventMsg.name)
  return name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void EventMsg::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:helium3.logging.EventMsg.name)
}
inline std::string* EventMsg::unsafe_arena_release_name() {
  // @@protoc_insertion_point(field_unsafe_arena_release:helium3.logging.EventMsg.name)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return name_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void EventMsg::unsafe_arena_set_allocated_name(
    std::string* name) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (name != nullptr) {
    
  } else {
    
  }
  name_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      name, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:helium3.logging.EventMsg.name)
}

// int64 start_ns = 4;
inline void EventMsg::clear_start_ns() {
  start_ns_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 EventMsg::_internal_start_ns() const {
  return start_ns_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 EventMsg::start_ns() const {
  // @@protoc_insertion_point(field_get:helium3.logging.EventMsg.start_ns)
  return _internal_start_ns();
}
inline void EventMsg::_internal_set_start_ns(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  start_ns_ = value;
}
inline void EventMsg::set_start_ns(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_start_ns(value);
  // @@protoc_insertion_point(field_set:helium3.logging.EventMsg.start_ns)
}

// int64 duration_ns = 5;
inline void EventMsg::clear_duration_ns() {
  duration_ns_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 EventMsg::_internal_duration_ns() const {
  return duration_ns_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 EventMsg::duration_ns() const {
  // @@protoc_insertion_point(field_get:helium3.logging.EventMsg.duration_ns)
  return _internal_duration_ns();
}
inline void EventMsg::_internal_set_duration_ns(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  duration_ns_ = value;
}
inline void EventMsg::set_duration_ns(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_duration_ns(value);
  // @@protoc_insertion_point(field_set:helium3.logging.EventMsg.duration_ns)
}

// string message = 6;
inline void EventMsg::clear_message() {
  message_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& EventMsg::message() const {
  // @@protoc_insertion_point(field_get:helium3.logging.EventMsg.message)
  return _internal_message();
}
inline void EventMsg::set_message(const std::string& value) {
  _internal_set_message(value);
  // @@protoc_insertion_point(field_set:helium3.logging.EventMsg.message)
}
inline std::string* EventMsg::mutable_message() {
  // @@protoc_insertion_point(field_mutable:helium3.logging.EventMsg.message)
  return _internal_mutable_message();
}
inline const std::string& EventMsg::_internal_message() const {
  return message_.Get();
}
inline void EventMsg::_internal_set_message(const std::string& value) {
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void EventMsg::set_message(std::string&& value) {
  
  message_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:helium3.logging.EventMsg.message)
}
inline void EventMsg::set_message(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:helium3.logging.EventMsg.message)
}
inline void EventMsg::set_message(const char* value,
    size_t size) {
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:helium3.logging.EventMsg.message)
}
inline std::string* EventMsg::_internal_mutable_message() {
  
  return message_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* EventMsg::release_message() {
  // @@protoc_insertion_point(field_release:helium3.logging.EventMsg.message)
  return message_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void EventMsg::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  message_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), message,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:helium3.logging.EventMsg.message)
}
inline std::string* EventMsg::unsafe_arena_release_message() {
  // @@protoc_insertion_point(field_unsafe_arena_release:helium3.logging.EventMsg.message)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return message_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void EventMsg::unsafe_arena_set_allocated_message(
    std::string* message) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (message != nullptr) {
    
  } else {
    
  }
  message_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      message, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:helium3.logging.EventMsg.message)
}

// bool complete = 7;
inline void EventMsg::clear_complete() {
  complete_ = false;
}
inline bool EventMsg::_internal_complete() const {
  return complete_;
}
inline bool EventMsg::complete() const {
  // @@protoc_insertion_point(field_get:helium3.logging.EventMsg.complete)
  return _internal_complete();
}
inline void EventMsg::_internal_set_complete(bool value) {
  
  complete_ = value;
}
inline void EventMsg::set_complete(bool value) {
  _internal_set_complete(value);
  // @@protoc_insertion_point(field_set:helium3.logging.EventMsg.complete)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace logging
}  // namespace helium3

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_event_2eproto
