# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: event.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65vent.proto\x12\x0fhelium3.logging\x1a\x1bgoogle/protobuf/empty.proto\"\x85\x01\n\x08\x45ventMsg\x12\x12\n\nmachine_id\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x01(\x05\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x10\n\x08start_ns\x18\x04 \x01(\x03\x12\x13\n\x0b\x64uration_ns\x18\x05 \x01(\x03\x12\x0f\n\x07message\x18\x06 \x01(\t\x12\x10\n\x08\x63omplete\x18\x07 \x01(\x08\x32G\n\x06Logger\x12=\n\x08LogEvent\x12\x19.helium3.logging.EventMsg\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENTMSG']._serialized_start=62
  _globals['_EVENTMSG']._serialized_end=195
  _globals['_LOGGER']._serialized_start=197
  _globals['_LOGGER']._serialized_end=268
# @@protoc_insertion_point(module_scope)
